/**
 * Clanker API v4 Features Example
 * Demonstrates new v4 API features while maintaining backward compatibility
 */

import { Clanker } from '../src/v4/index.js';
import { 
  generateRequestKey, 
  validateRequestKey,
  ensureRequestKey 
} from '../src/clanker-api/utils/index.js';
import { createWalletClient, createPublicClient, http, privateKeyToAccount } from 'viem';
import { base } from 'viem/chains';

// ============================================================================
// Setup
// ============================================================================

const account = privateKeyToAccount(process.env.PRIVATE_KEY as `0x${string}`);
const publicClient = createPublicClient({ 
  chain: base, 
  transport: http() 
});
const walletClient = createWalletClient({ 
  account, 
  chain: base, 
  transport: http() 
});

// Initialize Clanker with API support
const clanker = new Clanker({
  wallet: walletClient,
  publicClient: publicClient,
  api: {
    apiKey: process.env.CLANKER_API_KEY!,
  },
  operationMethod: 'auto',
});

// ============================================================================
// Example 1: Auto-Generated Request Keys
// ============================================================================

async function example1_AutoGeneratedRequestKeys() {
  console.log('\n=== Example 1: Auto-Generated Request Keys ===\n');
  
  // Generate a new request key
  const key1 = generateRequestKey();
  console.log('Generated key:', key1);
  console.log('Key length:', key1.length); // 32
  console.log('Is valid:', validateRequestKey(key1)); // true
  
  // Ensure a key exists (generate if not provided)
  const key2 = ensureRequestKey();
  console.log('\nAuto-generated key:', key2);
  
  // Use existing key if provided
  const existingKey = 'abcdef1234567890abcdef1234567890';
  const key3 = ensureRequestKey(existingKey);
  console.log('Using existing key:', key3);
  
  // Deploy token without specifying requestKey (auto-generated)
  const token = {
    name: 'Auto Key Token',
    symbol: 'AKT',
    tokenAdmin: account.address,
    image: 'ipfs://...',
    chainId: 8453,
  };
  
  console.log('\nDeploying token with auto-generated requestKey...');
  // The SDK will automatically generate a requestKey
  // const result = await clanker.deploy(token);
  console.log('✓ RequestKey will be auto-generated during deployment');
}

// ============================================================================
// Example 2: Get Tokens by Admin
// ============================================================================

async function example2_GetTokensByAdmin() {
  console.log('\n=== Example 2: Get Tokens by Admin ===\n');
  
  const adminAddress = account.address;
  
  // Get first page of tokens
  const result = await clanker.getTokensByAdmin(adminAddress);
  
  if (!result.success) {
    console.error('Error:', result.error);
    return;
  }
  
  console.log(`Total tokens managed: ${result.data.total}`);
  console.log(`Tokens on this page: ${result.data.data.length}\n`);
  
  // Display token information
  result.data.data.forEach((token, index) => {
    console.log(`${index + 1}. ${token.name} (${token.symbol})`);
    console.log(`   Address: ${token.contract_address}`);
    console.log(`   Chain: ${token.chain_id}`);
    console.log(`   Pool: ${token.pool_address || 'N/A'}`);
    console.log(`   Deployed: ${new Date(token.deployed_at).toLocaleDateString()}`);
    console.log('');
  });
  
  // Pagination example
  if (result.data.cursor) {
    console.log('More tokens available. Fetching next page...\n');
    
    const nextPage = await clanker.getTokensByAdmin(
      adminAddress,
      result.data.cursor,
      10 // limit
    );
    
    if (nextPage.success) {
      console.log(`Next page has ${nextPage.data.data.length} tokens`);
    }
  }
}

// ============================================================================
// Example 3: Get Uncollected Fees (v4 Enhanced)
// ============================================================================

async function example3_GetUncollectedFees() {
  console.log('\n=== Example 3: Get Uncollected Fees (v4) ===\n');
  
  // Example token address (replace with actual)
  const tokenAddress = '0x...' as `0x${string}`;
  const rewardRecipient = account.address;
  
  // For v4 tokens, specify the reward recipient address
  const result = await clanker.getUncollectedFees(
    tokenAddress,
    rewardRecipient
  );
  
  if (!result.success) {
    console.error('Error:', result.error);
    return;
  }
  
  console.log('Locker Address:', result.data.lockerAddress);
  console.log('LP NFT ID:', result.data.lpNftId);
  console.log('');
  
  // Token0 (usually the Clanker token)
  console.log(`${result.data.token0.name} (${result.data.token0.symbol}):`);
  console.log(`  Uncollected: ${result.data.token0UncollectedRewards}`);
  console.log(`  Decimals: ${result.data.token0.decimals}`);
  console.log('');
  
  // Token1 (usually WETH)
  console.log(`${result.data.token1.name} (${result.data.token1.symbol}):`);
  console.log(`  Uncollected: ${result.data.token1UncollectedRewards}`);
  console.log(`  Decimals: ${result.data.token1.decimals}`);
  
  // Calculate human-readable amounts
  const token0Amount = BigInt(result.data.token0UncollectedRewards) / 
    BigInt(10 ** result.data.token0.decimals);
  const token1Amount = BigInt(result.data.token1UncollectedRewards) / 
    BigInt(10 ** result.data.token1.decimals);
  
  console.log('\nHuman-readable amounts:');
  console.log(`  ${result.data.token0.symbol}: ${token0Amount}`);
  console.log(`  ${result.data.token1.symbol}: ${token1Amount}`);
}

// ============================================================================
// Example 4: Index Token
// ============================================================================

async function example4_IndexToken() {
  console.log('\n=== Example 4: Index Token ===\n');
  
  // Example token address (replace with actual)
  const tokenAddress = '0x...' as `0x${string}`;
  const chainId = 8453; // Base
  
  const result = await clanker.indexToken(
    tokenAddress,
    chainId,
    {
      name: 'My Indexed Token',
      symbol: 'MIT',
      image: 'https://example.com/token.png',
      description: 'A token indexed for visibility on clanker.world'
    }
  );
  
  if (!result.success) {
    console.error('Error:', result.error);
    return;
  }
  
  console.log('Index Status:', result.data.success ? 'Success' : 'Failed');
  console.log('Indexed:', result.data.indexed);
  
  if (result.data.tokenId) {
    console.log('Token ID:', result.data.tokenId);
  }
  
  if (result.data.message) {
    console.log('Message:', result.data.message);
  }
  
  if (result.data.indexed) {
    console.log(`\n✓ Token is now visible on clanker.world`);
    console.log(`  View at: https://clanker.world/clanker/${tokenAddress}`);
  }
}

// ============================================================================
// Example 5: Get Token Information
// ============================================================================

async function example5_GetTokenInfo() {
  console.log('\n=== Example 5: Get Token Information ===\n');
  
  // Example token address (replace with actual)
  const tokenAddress = '0x...' as `0x${string}`;
  
  const result = await clanker.getTokenInfo(tokenAddress);
  
  if (!result.success) {
    console.error('Error:', result.error);
    return;
  }
  
  console.log('Token Details:');
  console.log('─────────────────────────────────────');
  console.log(`Name: ${result.data.name}`);
  console.log(`Symbol: ${result.data.symbol}`);
  console.log(`Address: ${result.data.contract_address}`);
  console.log(`Admin: ${result.data.admin}`);
  console.log(`Chain ID: ${result.data.chain_id}`);
  console.log(`Pool Address: ${result.data.pool_address || 'N/A'}`);
  console.log(`Image: ${result.data.img_url || 'N/A'}`);
  console.log(`Deployed: ${new Date(result.data.deployed_at).toLocaleString()}`);
  
  if (result.data.description) {
    console.log(`\nDescription: ${result.data.description}`);
  }
  
  if (result.data.metadata) {
    console.log('\nMetadata:');
    console.log(JSON.stringify(result.data.metadata, null, 2));
  }
}

// ============================================================================
// Example 6: Get All Tokens (Paginated)
// ============================================================================

async function example6_GetAllTokens() {
  console.log('\n=== Example 6: Get All Tokens (Paginated) ===\n');
  
  const chainId = 8453; // Base
  const limit = 20;
  
  // Get first page
  const result = await clanker.getTokens(undefined, limit, chainId);
  
  if (!result.success) {
    console.error('Error:', result.error);
    return;
  }
  
  console.log(`Total tokens on chain ${chainId}: ${result.data.total}`);
  console.log(`Showing ${result.data.data.length} tokens:\n`);
  
  // Display tokens
  result.data.data.forEach((token, index) => {
    console.log(`${index + 1}. ${token.name} (${token.symbol})`);
    console.log(`   ${token.contract_address}`);
  });
  
  // Pagination example - fetch all tokens
  if (result.data.cursor) {
    console.log('\n📄 More pages available');
    console.log(`   Use cursor: ${result.data.cursor.substring(0, 20)}...`);
  }
}

// ============================================================================
// Example 7: Complete Token Management Dashboard
// ============================================================================

async function example7_TokenDashboard() {
  console.log('\n=== Example 7: Token Management Dashboard ===\n');
  
  const adminAddress = account.address;
  
  // Get all tokens managed by this address
  const tokensResult = await clanker.getTokensByAdmin(adminAddress);
  
  if (!tokensResult.success) {
    console.error('Failed to fetch tokens:', tokensResult.error);
    return;
  }
  
  console.log(`Managing ${tokensResult.data.total} tokens\n`);
  console.log('═══════════════════════════════════════════════════════════\n');
  
  // For each token, get detailed info and fees
  for (const token of tokensResult.data.data.slice(0, 3)) { // Limit to 3 for demo
    console.log(`${token.name} (${token.symbol})`);
    console.log('─────────────────────────────────────');
    console.log(`Address: ${token.contract_address}`);
    console.log(`Chain: ${token.chain_id}`);
    console.log(`Pool: ${token.pool_address || 'N/A'}`);
    console.log(`Deployed: ${new Date(token.deployed_at).toLocaleDateString()}`);
    
    // Get uncollected fees
    const feesResult = await clanker.getUncollectedFees(
      token.contract_address as `0x${string}`,
      adminAddress
    );
    
    if (feesResult.success) {
      console.log('\nUncollected Fees:');
      console.log(`  ${feesResult.data.token0.symbol}: ${feesResult.data.token0UncollectedRewards}`);
      console.log(`  ${feesResult.data.token1.symbol}: ${feesResult.data.token1UncollectedRewards}`);
    }
    
    console.log('\n');
  }
  
  console.log('═══════════════════════════════════════════════════════════\n');
}

// ============================================================================
// Example 8: Backward Compatibility
// ============================================================================

async function example8_BackwardCompatibility() {
  console.log('\n=== Example 8: Backward Compatibility ===\n');
  
  // Old code still works exactly as before
  const oldStyleClanker = new Clanker({
    wallet: walletClient,
    publicClient: publicClient,
  });
  
  console.log('✓ Old-style initialization works');
  
  // Deploy token the old way (still works)
  const token = {
    name: 'Legacy Token',
    symbol: 'LGC',
    tokenAdmin: account.address,
    chainId: 8453,
  };
  
  console.log('✓ Old-style token configuration works');
  
  // New features gracefully degrade without API key
  const result = await oldStyleClanker.getTokensByAdmin(account.address);
  
  if (!result.success) {
    console.log('✓ New methods return helpful error without API key:');
    console.log(`  "${result.error}"`);
  }
  
  console.log('\n✓ Full backward compatibility maintained!');
}

// ============================================================================
// Run Examples
// ============================================================================

async function main() {
  console.log('╔═══════════════════════════════════════════════════════════╗');
  console.log('║     Clanker API v4 Features - Example Demonstrations     ║');
  console.log('╚═══════════════════════════════════════════════════════════╝');
  
  try {
    // Run all examples
    await example1_AutoGeneratedRequestKeys();
    await example2_GetTokensByAdmin();
    // await example3_GetUncollectedFees(); // Requires actual token
    // await example4_IndexToken(); // Requires actual token
    // await example5_GetTokenInfo(); // Requires actual token
    await example6_GetAllTokens();
    // await example7_TokenDashboard(); // Requires tokens
    await example8_BackwardCompatibility();
    
    console.log('\n✓ All examples completed successfully!');
    
  } catch (error) {
    console.error('\n❌ Error running examples:', error);
  }
}

// Run if executed directly
if (import.meta.url === `file://${process.argv[1]}`) {
  main().catch(console.error);
}

export {
  example1_AutoGeneratedRequestKeys,
  example2_GetTokensByAdmin,
  example3_GetUncollectedFees,
  example4_IndexToken,
  example5_GetTokenInfo,
  example6_GetAllTokens,
  example7_TokenDashboard,
  example8_BackwardCompatibility,
};
